name: pull request ci
on:
  pull_request:
    branches: [ develop ]

jobs:
  ci-test: 
    runs-on: ubuntu-latest 
    steps: 
    - name: check out git repository
      uses: actions/checkout@v4  

    - name: dir list
      run: ls -al
      
    - name: Set up JDK 11 
      uses: actions/setup-java@v4
      with:
        java-version: 11 
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test

    - name: fail build
      if: ${{ failure() }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.TOKEN }}
        script: |
          const pull_number = ${{ github.event.pull_request.number }}
          const updated_title = `[BUILD FAIL] ${{ github.event.pull_request.title }}`
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pull_number,
            body: '빌드에 실패했습니다.',
            event: 'REQUEST_CHANGES'
          })
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pull_number,
            title: updated_title,
            state: 'closed'
          })
